server:
  port: 8096
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: part-time-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka